### ISSUE TITLE
question: Plotting a weighted graph

### ISSUE THREAD

**Issue by lulopolar** [aestrivex/cvu#3]
Hi @aestrivex , I just discovered your repository and am curious to know how your are making the graph plots with weighed edges.  What I am doing at the moment is to plot the cortical surfaces with pysurfer, and then:

pts = mlab.points3d(xyz)
pts.mlab_source.dataset.lines = edges
tube = mlab.pipeline.tube(args)
mlab.pipeline.surface(args).

This is fast, but I have not been able to figure out how to modify the edge properties. I tried to loop thorough the edges and add every line individually, and could indeed modify the line properties to get the weighted effect, but it was painfully slow. Can you give me few pointers as to how you do this?
Thanks!

**Comment by aestrivex** [comment]
Hi,

There are several ways of doing it, the best way is
```
vecs=mlab.pipeline.vector_scatter(xyz)
mlab.pipeline.vector(vecs)
```
Look at [vectors_gen()](https://github.com/aestrivex/cvu/blob/master/cvu/dataview.py#L255-298)

**Comment by lulopolar** [comment]
Awesome, Thanks a million!
