### ISSUE TITLE
ImportError on launching cvu

### ISSUE THREAD

**Issue by umeshiso** [aestrivex/cvu#4]
Hi there,

I've been having trouble starting cvu after installing the package, along with an academic version of Enthought Canopy. I think I've satisfied all the dependencies, but get the error below upon starting cvu. Not sure if this problem is peculiar to my system (64-bit iMac running OS X v. 10.10.3), but it seems like there's an import call made to "mne.fixes" that directly results in the error. Any suggestions you have would be very much appreciated. Thanks!

Traceback (most recent call last):
  File "/Users/blah/Library/Enthought/Canopy_64bit/User/bin/cvu", line 4, in <module>
    __import__('pkg_resources').run_script('cvu==0.4.3', 'cvu')
  File "/Users/blah/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/blah/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/Users/blah/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/cvu-0.4.3-py2.7.egg/EGG-INFO/scripts/cvu", line 33, in <module>
    from cvu.main import main
  File "/Users/blah/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/cvu-0.4.3-py2.7.egg/cvu/__init__.py", line 20, in <module>
    from .main import load_adj, load_parc, usage, main
  File "/Users/blah/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/cvu-0.4.3-py2.7.egg/cvu/main.py", line 20, in <module>
    from gui import CvuGUI,ErrorHandler
  File "/Users/blah/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/cvu-0.4.3-py2.7.egg/cvu/gui.py", line 24, in <module>
    from dataset import Dataset
  File "/Users/blah/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/cvu-0.4.3-py2.7.egg/cvu/dataset.py", line 26, in <module>
    from dataview import (DataView,DVMayavi,DVMatrix,DVCircle)
  File "/Users/blah/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/cvu-0.4.3-py2.7.egg/cvu/dataview.py", line 32, in <module>
    import circle_plot
  File "/Users/blah/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/cvu-0.4.3-py2.7.egg/cvu/circle_plot.py", line 25, in <module>
    from mne.fixes import tril_indices
ImportError: No module named fixes

**Comment by aestrivex** [comment]
Hi,

what version of mne-python are you using? mne-python has changed their APIs
numerous times over the past few years and previously the tril_indices()
function was in some other module.

On my box running a development version of mne version 0.10 the function is
in mne.fixes and it should also be in the latest stable release.

**Comment by umeshiso** [comment]
I've installed version 0.2-1, which was suggested by the Canopy package
manager. I could try hunting down an older version and manually installing
it, if that's the most expedient way.

**Comment by aestrivex** [comment]
Version 0.2.1 is three or four years old. The canopy package manager is not
very good; it indexes very old stable pypi packages and mirrors them. Try
downloading a newer version with pip.

**Comment by umeshiso** [comment]
Hi Roan,

Thanks for your help with this. Upgrading MNE got me past my immediate
issue, but I'm afraid the UI is still pretty dysfunctional. Clicking any of
the load buttons (e.g., "Load a parcellation") gives an error in the
terminal (see below), with no response in the UI. Clicking the yellow icon
in the upper left corner of the UI results in an immediate crash of the UI.
Some but not all other elements of the UI are responsive. If I can provide
any more information about library versions, etc., I'll be glad to--the
software sounds very useful for my research, and I'd love to get it working.

umeshiso

On clicking "Load a parcellation":

Traceback (most recent call last):
  File
"/Users/jeffreyphillips/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traits/trait_notifiers.py",
line 340, in __call__
    self.handler( *args )
  File
"/Users/jeffreyphillips/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/cvu-0.4.3-py2.7.egg/cvu/gui.py",
line 245, in _load_parcellation_button_fired
    self.parcellation_chooser_window.edit_traits()
  File
"/Users/jeffreyphillips/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/handler.py",
line 445, in edit_traits
    self.trait_view_elements(), handler, id, scrollable, args )
  File
"/Users/jeffreyphillips/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/view.py",
line 433, in ui
    ui.ui( parent, kind )
  File
"/Users/jeffreyphillips/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/ui.py",
line 221, in ui
    self.rebuild( self, parent )
  File
"/Users/jeffreyphillips/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/wx/toolkit.py",
line 140, in ui_live
    ui_live.ui_live( ui, parent )
  File
"/Users/jeffreyphillips/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/wx/ui_live.py",
line 68, in ui_live
    ui_dialog( ui, parent, NONMODAL )
  File
"/Users/jeffreyphillips/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/wx/ui_live.py",
line 99, in ui_dialog
    ui.owner.init( ui, parent, style )
  File
"/Users/jeffreyphillips/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/wx/ui_live.py",
line 223, in init
    sw = panel( ui, window )
  File
"/Users/jeffreyphillips/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/wx/ui_panel.py",
line 349, in panel
    content[0], ui )
  File
"/Users/jeffreyphillips/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/wx/ui_panel.py",
line 523, in fill_panel_for_group
    create_panel )
  File
"/Users/jeffreyphillips/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/wx/ui_panel.py",
line 670, in __init__
    self.add_groups( content, panel )
  File
"/Users/jeffreyphillips/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/wx/ui_panel.py",
line 822, in add_groups
    fill_panel_for_group( panel, subgroup, self.ui )
  File
"/Users/jeffreyphillips/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/wx/ui_panel.py",
line 523, in fill_panel_for_group
    create_panel )
  File
"/Users/jeffreyphillips/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/wx/ui_panel.py",
line 672, in __init__
    self.add_items(content, panel, self.sizer)
  File
"/Users/jeffreyphillips/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/wx/ui_panel.py",
line 1031, in add_items
    editor.prepare( item_panel )
  File
"/Users/jeffreyphillips/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/editor.py",
line 158, in prepare
    self.update_editor()
  File
"/Users/jeffreyphillips/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/cvu-0.4.3-py2.7.egg/cvu/custom_file_editor.py",
line 161, in update_editor
    set_text(self, self.value)
  File
"/Users/jeffreyphillips/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/cvu-0.4.3-py2.7.egg/cvu/custom_file_editor.py",
line 110, in set_text
    if _tk == 'wx': return editor.text_control.SetValue(text)
AttributeError: 'NoneType' object has no attribute 'SetValue'

**Comment by aestrivex** [comment]
How recently did you download canopy?

I haven't seen this problem before and I think it will take me a little
while to debug. In the meantime you might be able to get cvu to more
immediately work with anaconda instead which doesn't use the wx editor
which is the thing that crashed according to the debug output.

**Comment by umeshiso** [comment]
This is a brand-new installation of canopy--from Tuesday or Wednesday. I've
just tried with an anaconda installation and received a number of
Qt-related errors, with the UI failing to open. If it's helpful, I can send
you the error report.

Thanks for all your help,

Jeff

**Comment by aestrivex** [comment]
Sure, if show me the errors I might be able to fix those more easily.

**Comment by aestrivex** [comment]
Please create a new issue report with specific error messages if the error persists.
