### ISSUE TITLE
Installation issue?

### ISSUE THREAD

**Issue by luckydjuju** [aestrivex/cvu#5]
Hi Roan,
I heard about your toolbox (from Sepideh Sadaghiani at an advanced neuroimaging course -- congrats!) and thought I'd give it a whirl. I got stuck during the install unfortunately...
I think I install all dependencies. 
When I launch cvu (either directly by typing 'cmu', or in the download folder './run'), I get:
*** Error in `python': malloc(): memory corruption: 0x0000000004407350 **
I am running Ubuntu 14.04 on a ThinkPad W530.
Let me know if you have any idea what I should do to troubleshoot this.
- Julien

**Comment by aestrivex** [comment]
Hi,

Unfortunately there's almost nothing useful I can say about that error. It
could suggest a hardware problem. If I saw that error persisting across
reboots, I would check for hardware issues, e.g. faulty memory.
